pipeline {
 agent any
 tools {
  maven 'apache-maven-3.8.6'
 }

    stages {
        stage('Build') {
            steps {
               echo 'Building...'
            }
        }
        stage('Test') {
         steps{
         echo "Testing..."
         snykSecurity(
                    snykInstallation: 'snyk@latest',
                    snykTokenId: 'organisation-snyk-api-token',
                    additionalArguments: '--debug --all-projects'
                )
         }
            
        }
        stage('Done') {
            steps {
                echo 'Done...'
            }
        }
    }
}
