pipeline {
 agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
         steps{
         echo "Testing..."
         snykSecurity(
                    snykInstallation: 'snyk@latest',
                    snykTokenId: 'organisation-snyk-api-token',
                    additionalArguments: '--debug --all-projects'
                )
         }
            
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
